import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import ReactMarkdown from'react-markdown';import remarkGfm from'remark-gfm';import{createAgentClient}from'./client';import'./style.css';
type Workspace={ID:string;Name:string;Root:string};type Session={ID:string;Title:string};type Message={ID:string;Role:string;Content:string};type Task={ID:string;Objective:string;Status:string;Result:string;Error:string};type Node={ID:string;Title:string;Status:string;DependsOn:string[]};type Approval={ID:string;TaskID:string;ToolName:string;Arguments:string;RiskLevel:string;Reason:string;Status:string};
const token=localStorage.getItem('wbot_token')||'',client=createAgentClient();const api=(path:string,init?:RequestInit)=>client.request(path,init);
const compact=(value:unknown,max=120)=>{const text=typeof value==='string'?value:JSON.stringify(value);const line=(text||'').replace(/\s+/g,' ').trim();return line.length>max?line.slice(0,max-1)+'…':line};
function Markdown({children,className='' }:{children:string;className?:string}){return <div className={`markdown ${className}`}><ReactMarkdown remarkPlugins={[remarkGfm]}>{children}</ReactMarkdown></div>}
function MessageBody({message}:{message:Message}){if(message.Role==='assistant'&&message.Content.startsWith('TOOL_CALL ')){try{const call=JSON.parse(message.Content.slice(10));const args=call.Arguments||{};const preview=args.command||args.path||args.problem||args;return <details className="tool-entry"><summary><span>工具调用</span><code>{call.Name||'unknown'}</code><small>{compact(preview)}</small></summary><pre className="tool-json">{JSON.stringify(call,null,2)}</pre></details>}catch{return <pre>{message.Content}</pre>}}if(message.Role==='tool'){try{const result=JSON.parse(message.Content);const preview=result.Summary||result.Error?.Message||result.Data?.output||result.Data;return <details className="tool-entry"><summary><span>工具结果</span><code className={result.Status}>{result.Status||'unknown'}</code><small>{compact(preview)}</small></summary><pre className="tool-json">{JSON.stringify(result,null,2)}</pre></details>}catch{return <pre>{message.Content}</pre>}}if(message.Role==='assistant')return <Markdown>{message.Content}</Markdown>;return <pre>{message.Content}</pre>}
function App(){const[workspaces,setWorkspaces]=useState<Workspace[]>([]),[session,setSession]=useState<Session|null>(null),[messages,setMessages]=useState<Message[]>([]),[tasks,setTasks]=useState<Task[]>([]),[nodes,setNodes]=useState<Record<string,Node[]>>({}),[approvals,setApprovals]=useState<Approval[]>([]),[text,setText]=useState(''),[error,setError]=useState(''),[needsAuth,setNeedsAuth]=useState(false),[loginToken,setLoginToken]=useState('');
 const handleError=(e:any)=>{if(e?.status===401||e?.message==='unauthorized')setNeedsAuth(true);else setError(e?.message||String(e))};const refreshWorkspaces=()=>api('/api/v1/workspaces').then(x=>setWorkspaces(x||[])).catch(handleError);const refresh=()=>{if(!session)return;api(`/api/v1/sessions/${session.ID}`).then(async x=>{setMessages(x.messages||[]);const nextTasks:Task[]=x.tasks||[];setTasks(nextTasks);const failed=nextTasks.find(t=>t.Status==='failed'&&t.Error);if(failed)setError(failed.Error);const details=await Promise.all(nextTasks.map((t:Task)=>api(`/api/v1/tasks/${t.ID}`)));setNodes(Object.fromEntries(details.map((d:any)=>[d.task.ID,d.nodes||[]])))}).catch(handleError);api('/api/v1/approvals?status=pending').then(x=>setApprovals(x||[])).catch(handleError)};
 useEffect(()=>{refreshWorkspaces();if(token)api('/api/v1/auth/session',{method:'POST'}).catch(()=>{})},[]);useEffect(()=>{if(!session)return;refresh();const es=new EventSource(client.eventsURL(session.ID),{withCredentials:true});es.onmessage=refresh;const poll=window.setInterval(refresh,2000);return()=>{window.clearInterval(poll);es.close()}},[session?.ID]);
 async function open(){try{const w=await api('/api/v1/workspaces/open',{method:'POST',body:JSON.stringify({name:'默认工作区'})});setWorkspaces(x=>[...x,w])}catch(e:any){setError(e.message)}}
 async function create(w:Workspace){try{const s=await api('/api/v1/sessions',{method:'POST',body:JSON.stringify({workspaceId:w.ID,title:'新会话'})});setError('');setSession(s)}catch(e:any){handleError(e)}}
 async function send(){if(!session){setError('请先新建会话，再发送消息。');return}if(!text.trim())return;const v=text;setText('');try{await api(`/api/v1/sessions/${session.ID}/messages`,{method:'POST',body:JSON.stringify({content:v})});refresh()}catch(e:any){setText(v);handleError(e)}}
 async function decide(a:Approval,d:string){await api(`/api/v1/approvals/${a.ID}/${d}`,{method:'POST'});refresh()}
 function login(){if(!loginToken.trim())return;localStorage.setItem('wbot_token',loginToken.trim());location.reload()}
 if(needsAuth)return <div style={{minHeight:'100vh',display:'grid',placeItems:'center',background:'#f3f5f1'}}><div style={{width:380,maxWidth:'90vw',padding:32,background:'white',borderRadius:16,boxShadow:'0 16px 50px #173b2820'}}><div className="brand">wbot<span>安全登录</span></div><h2 style={{marginBottom:10}}>连接 Agent Runtime</h2><p style={{color:'#718076',lineHeight:1.6}}>服务端已启用访问认证，请输入启动时配置的 <code>WBOT_AUTH_TOKEN</code>。</p><input autoFocus type="password" value={loginToken} onChange={e=>setLoginToken(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')login()}} placeholder="访问 Token" style={{width:'100%',padding:12,border:'1px solid #ccd4ce',borderRadius:9,margin:'10px 0 14px'}}/><button onClick={login} style={{width:'100%'}}>登录</button></div></div>;
 return <div className="app"><aside><div className="brand">wbot<span>自主工作台</span></div><button onClick={open}>＋ 打开默认工作区</button>{workspaces.map(w=><div className="workspace" key={w.ID}><b>{w.Name}</b><small>{w.Root}</small><button onClick={()=>create(w)}>新建会话</button></div>)}</aside><main><header><div><h2>{session?.Title||'选择或新建会话'}</h2><small>{session?.ID}</small></div><span className="status">● Runtime</span></header>{error&&<div className="error" onClick={()=>setError('')}>{error}</div>}<section className="messages">{messages.map(m=><article className={m.Role} key={m.ID}><label>{m.Role}</label><MessageBody message={m}/></article>)}{!messages.length&&<div className="empty">创建会话后，告诉 wbot 你要完成的目标。</div>}</section><div className="composer"><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.repeat&&!e.nativeEvent.isComposing){e.preventDefault();send()}}} placeholder="输入目标，Enter 发送，Shift + Enter 换行"/><button onClick={send}>发送</button></div></main><aside className="right"><h3>任务图</h3>{tasks.map(t=><div className="card" key={t.ID}><div><b>{t.Objective}</b><i className={t.Status}>{t.Status}</i></div><ol className="nodes">{(nodes[t.ID]||[]).map(n=><li key={n.ID}><span>{n.Title}</span><i className={n.Status}>{n.Status}</i>{n.DependsOn?.length>0&&<small>依赖 {n.DependsOn.length} 项</small>}</li>)}</ol>{t.Result&&<Markdown className="task-result">{t.Result}</Markdown>}{t.Error&&<p className="red">{t.Error}</p>}</div>)}<h3>待审批</h3>{approvals.filter(a=>!session||tasks.some(t=>t.ID===a.TaskID)).map(a=><div className="card approval" key={a.ID}><b>{a.ToolName} · {a.RiskLevel}</b><p>{a.Reason}</p><code>{a.Arguments}</code><div><button onClick={()=>decide(a,'approve')}>批准</button><button className="danger" onClick={()=>decide(a,'reject')}>拒绝</button></div></div>)}</aside></div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
